### PR TITLE
fix input output checking

### LINKED ISSUE #507: Introspection compiles but returns invalid schema at runtime if you include a normal object in an input object
### Environment

* Elixir version (elixir -v): 1.6.1
* Absinthe version (mix deps | grep absinthe): 1.4.7 
* Client Framework and version (Relay, Apollo, etc): Any client

### Expected behavior

Invalid input objects raise a compile time, or at least a runtime error.

### Actual behavior

Schema with invalid input object does not raise any error, but the generated introspection schema is invalid. Different clients fail in different ways. `graphql-cli` fails like this:

`Introspection must provide input type for arguments.`

### Steps to reproduce

Create an input object like this:

```elixir

object :my_object do
  field :anything, :string
end

input_object :some_input do
  field :bad, :my_object
end

```

### PR DESCRIPTION
**Pull request by benwilson512**
Fixes #507

### CODE REVIEW

**Comment by corck** [comment]
@benwilson512  Any plans to release the changes into a new version, just ran into the same problem.

File: test/support/fixtures/dynamic/invalid_input_types.exs [hunk 1]
```diff
@@ -1,19 +1,16 @@
-defmodule Absinthe.Fixtures.InvalidInputTypesSchema do
```
Comment (jessedijkstra) [inline test/support/fixtures/dynamic/invalid_input_types.exs]: Don't you have the file names the other way around now? InvalidOutputTypesSchema is in the invalid_input_types.exs file and the other way around.

File: test/support/case/assertions/schema.ex [hunk 2]
```diff
@@ -20,6 +20,8 @@ defmodule Absinthe.Case.Assertions.Schema do
         load_schema(schema_name)
       end
 
+    err |> IO.inspect()
```
Comment (jessedijkstra) [inline test/support/case/assertions/schema.ex]: Forgot a debug statement?
