### PR TITLE
Fix type resolution by recursing prototypes

### LINKED ISSUE #1279: Introspection query fails when using a prototype schema that defines types for use by directive arguments
If submitting a bug, please provide the following:

### Environment

* Elixir version (elixir -v): 1.14.4
* Absinthe version (mix deps | grep absinthe): 1.7.5
* Client Framework and version (Relay, Apollo, etc): N/A

### Expected behavior

When using a prototype schema that defines directives as well as types used for the directives' arguments, the introspection query should succeed and return directives used by the schema as well as the argument types.

### Actual behavior

The introspection query fails:
```elixir
iex(1)> Absinthe.Schema.introspect(MyAppWeb.Schema)
{:ok,
 %{
   data: %{"__schema" => nil},
   errors: [
     %{
       locations: [%{column: 3, line: 64}],
       message: "Cannot return null for non-nullable field",
       path: ["__schema", "directives", 2, "args", 0, "type"]
     }
   ]
 }}
```

Poking around the schema (not the prototype schema) using `Absinthe.Schema.lookup_*` functions reveals that the directives resolve properly but looking up the custom argument types returns `nil`:
<details>
  <summary>iex output</summary>

  ```elixir
  iex(1)> Absinthe.Schema.lookup_directive(MyAppWeb.Schema, "feature")
  %Absinthe.Type.Directive{
    name: "feature",
    description: nil,
    identifier: :feature,
    args: %{
      complex: %Absinthe.Type.Argument{
        identifier: :complex,
        name: "complex",
        description: nil,
        type: :complex,
        deprecation: nil,
        default_value: nil,
        definition: nil,
        __reference__: nil
      },
      name: %Absinthe.Type.Argument{
        identifier: :name,
        name: "name",
        description: nil,
        type: %Absinthe.Type.NonNull{of_type: :string},
        deprecation: nil,
        default_value: nil,
        definition: nil,
        __reference__: nil
      },
      number: %Absinthe.Type.Argument{
        identifier: :number,
        name: "number",
        description: nil,
        type: :integer,
        deprecation: nil,
        default_value: nil,
        definition: nil,
        __reference__: nil
      }
    },
    locations: [:argument_definition, :enum, :enum_value, :field_definition,
    :input_field_definition, :input_object, :interface, :object, :scalar,
    :schema, :union],
    expand: {:ref, MyAppWeb.SchemaPrototype,
    {Absinthe.Blueprint.Schema.DirectiveDefinition, :feature}},
    definition: MyAppWeb.SchemaPrototype,
    repeatable: true,
    __private__: [],
    __reference__: %{
      location: %{
        file: "/home/david/Documents/com5737-repro/repro/lib/my_app_web/schema_prototype.ex",
        line: 12
      },
      module: MyAppWeb.SchemaPrototype
    }
  }
  iex(2)> Absinthe.Schema.lookup_type(MyAppWeb.Schema, "Complex")     
  nil
  iex(3)> Absinthe.Schema.lookup_type(MyAppWeb.SchemaPrototype, "Complex")
  %Absinthe.Type.InputObject{
    name: "Complex",
    description: nil,
    fields: %{
      str: %Absinthe.Type.Field{
        identifier: :str,
        name: "str",
        description: nil,
        type: :string,
        deprecation: nil,
        args: %{},
        config: nil,
        triggers: [],
        middleware: [],
        complexity: nil,
        default_value: nil,
        __private__: [],
        definition: MyAppWeb.SchemaPrototype,
        __reference__: %{
          location: %{
            file: "/home/david/Documents/com5737-repro/repro/lib/my_app_web/schema_prototype.ex",
            line: 5
          },
          module: MyAppWeb.SchemaPrototype
        }
      }
    },
    identifier: :complex,
    __private__: [__absinthe_referenced__: true],
    definition: MyAppWeb.SchemaPrototype,
    __reference__: %{
      location: %{
        file: "/home/david/Documents/com5737-repro/repro/lib/my_app_web/schema_prototype.ex",
        line: 4
      },
      module: MyAppWeb.SchemaPrototype
    }
  }
  ```
</details>

### Relevant Schema/Middleware Code
I really just copied the schemas from [`type_system_directive_test.exs`](https://github.com/absinthe-graphql/absinthe/blob/master/test/absinthe/schema/type_system_directive_test.exs).

#### Prototype schema
<details>
  <summary>Code</summary>

  ```elixir
  defmodule MyAppWeb.SchemaPrototype do
    use Absinthe.Schema.Prototype

    input_object :complex do
      field :str, :string
    end

    directive :external do
      on [:field_definition]
    end

    directive :feature do
      arg :name, non_null(:string)
      arg :number, :integer
      arg :complex, :complex

      repeatable true

      on [
        :schema,
        :scalar,
        :object,
        :field_definition,
        :argument_definition,
        :interface,
        :union,
        :enum,
        :enum_value,
        :input_object,
        :input_field_definition
      ]
    end
  end
  ```
</details>

#### Schema
<details>
  <summary>Code</summary>

  ```elixir
  defmodule MyAppWeb.Schema do
    use Absinthe.Schema

    @prototype_schema MyAppWeb.SchemaPrototype

    schema do
      directive :feature, name: ":schema"
      field :query, :query
    end

    query do
      field :post, :post do
        directive :feature, name: ":field_definition"
      end

      field :sweet, :sweet_scalar
      field :which, :category
      field :pet, :dog

      field :search, :search_result do
        arg :filter, :search_filter, directives: [{:feature, name: ":argument_definition"}]
        directive :feature, name: ":argument_definition"
      end
    end

    object :post do
      directive :feature, name: ":object", number: 3

      field :name, :string do
        deprecate "Bye"
      end
    end

    scalar :sweet_scalar do
      directive :feature, name: ":scalar"
      parse &Function.identity/1
      serialize &Function.identity/1
    end

    enum :category do
      directive :feature, name: ":enum"
      value :this
      value :that, directives: [feature: [name: ":enum_value"]]
      value :the_other, directives: [deprecated: [reason: "It's old"]]
    end

    interface :animal do
      directive :feature, name: ":interface"

      field :leg_count, non_null(:integer) do
        directive :feature,
          name: """
          Multiline here?
          Second line
          """
      end
    end

    object :dog do
      is_type_of fn _ -> true end
      interface :animal
      field :leg_count, non_null(:integer)
      field :name, non_null(:string), directives: [:external]
    end

    input_object :search_filter do
      directive :feature, name: ":input_object"

      field :query, :string, default_value: "default" do
        directive :feature, name: ":input_field_definition"
      end
    end

    union :search_result do
      directive :feature, name: ":union"
      types [:dog, :post]

      resolve_type fn %{type: type}, _ -> type end
    end
  end
  ```
</details>

### PR DESCRIPTION
**Pull request by jeffutter**
This fixes an issue when you have types declared in a Prototype (such as input_object input types for a directive). Previously type resolution would look on the Schema, but not the Prototype for the type definitions.

You _could_ workaround this by duplicating your type definition into both the Schema and the Prototype. This makes me somewhat curious if there is a better way to fix this, in that the code that was trying to resolve the type here shouldn't be resolving it on the Schema, but rather on the Prototype 🤷. This seems to work though.

Fixes #1279

Also should fix the issue mentioned here: https://github.com/DivvyPayHQ/absinthe_federation/pull/81

### CODE REVIEW

File: test/absinthe/introspection_test.exs [hunk 1]
```diff
@@ -89,6 +89,88 @@ defmodule Absinthe.IntrospectionTest do
...
   end
 
+  describe "introspection of complex directives" do
+    defmodule ComplexDirectiveSchema do
+      use Absinthe.Schema
+      use Absinthe.Fixture
+
+      defmodule ComplexDirectivePrototype do
+        use Absinthe.Schema.Prototype
+
```
Comment (kzlsakal) [inline test/absinthe/introspection_test.exs:99]: @jeffutter thank you so much for looking into this!

Would you be able to add a scalar and an enum type to this prototype and use those in the directive arguments to ensure that's handled as well?

**Comment by jeffutter** [comment]
⏸️  I just realized that the fixed test is broken with `SCHEMA_PROVIDER=persistent_term` (didn't realize that setting was run in CI). So I'll implement `persistent_term` shortly and expand the test as @kzlsakal  suggested.

File: test/absinthe/introspection_test.exs (hunk 1 above)
Comment (kzlsakal) [reply test/absinthe/introspection_test.exs:104]: @jeffutter I can't resolve my previous comment for some reason so I'll respond to your last message here

> I just realized that the fixed test is broken with `SCHEMA_PROVIDER=persistent_term` (didn't realize that setting was run in CI). So I'll implement `persistent_term` shortly and expand the test as @kzlsakal suggested.
> 
> Done: ✅

I did some testing with our service which uses both absinthe_federation and absinthe. I think this change is super close (thanks for adding the fixes for persistent term as well). Although during my testing, I found that absinthe_federation specifies a `name` for the `:_field_set` scalar [here](https://github.com/DivvyPayHQ/absinthe_federation/blob/main/lib/absinthe/federation/schema/prototype/federated_directives.ex#L12) which starts with an underscore. When I tried to change apply this to your test and changed the scalar definition to 

```elixir
scalar :_normal_string, name: "_NormalString", description: "string" do
```

The output of the `complex_directive_args` you're testing below became this:

```elixir
[
  %{"defaultValue" => nil, "description" => nil, "name" => "colorChannel", "type" => %{"kind" => "ENUM", "name" => "ColorChannel"}},
  %{"defaultValue" => nil, "description" => nil, "name" => "complex", "type" => %{"kind" => "INPUT_OBJECT", "name" => "Complex"}},
  %{"defaultValue" => nil, "description" => nil, "name" => "normalString", "type" => %{"kind" => "SCALAR", "name" => "_NormalString"}}
]
```

as you can see while the "type" is correct, the underscore from the name of its parent is stripped. This eventually causes the following error when I try to run the introspection query on the actual endpoint that uses absinthe federation:

```
Error: Invalid or incomplete schema, unknown type: _FieldSet. Ensure that a full introspection query is used in order to build a client schema.
```

hope that helps!

Comment (kzlsakal) [reply test/absinthe/introspection_test.exs:104]: Although I can confirm this PR resolves the issue with the introspection query receiving a GraphQL error (`Cannot return null for non-nullable field`) in the first place.

Comment (kzlsakal) [reply test/absinthe/introspection_test.exs:104]: I think the introspection parser expects those types to be defined in the __schema.types path when you add the following to your query:

```graphql
query IntrospectionQuery {
  __schema {
    types {
      name
    }
    directives {
      ...
```

Comment (jeffutter) [reply test/absinthe/introspection_test.exs:104]: Hmmm. I was using a very simple project with AbsintheFederation and was able to print the introspection query. Perhaps it was too simple to hit that. I’ll try to construct a more complex example over the weekend.

Comment (kzlsakal) [reply test/absinthe/introspection_test.exs:104]: @jeffutter just tested after your [1f8122e](https://github.com/absinthe-graphql/absinthe/pull/1334/commits/1f8122edd524dd4850e95a548bc62077d08b42a4) update. Works like a charm 👏

Comment (jeffutter) [reply test/absinthe/introspection_test.exs:104]: Woo that was fast :-D 💨 . I just verified with GraphiQL and came here to ping you, you beat me too it 🤣

**Review by japhib — APPROVED** [review]

**Comment by benwilson512** [comment]
Huh I'm surprised the CI isn't running on this. Will review

**Comment by jeffutter** [comment]
> Huh I'm surprised the CI isn't running on this. Will review

Did the main branch change from `master` to `main` recently? It looks like CI is setup for PRs against `master`, I opened this against `main` since it seems to be the default branch.

https://github.com/absinthe-graphql/absinthe/blob/ff726c88a87d7031fc0bfb30f1a7b174168d985e/.github/workflows/elixir.yml#L3C1-L8C1

**Comment by jeffutter** [comment]
I rebased this off the latest `main`, CI should run once the workflow is approved.

**Review by benwilson512 — APPROVED** [review]

**Comment by benwilson512** [comment]
Thanks!
